/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
	interface ElectionNavbar {}
}
declare global {
	interface HTMLElectionNavbarElement
		extends Components.ElectionNavbar, HTMLStencilElement {}
	var HTMLElectionNavbarElement: {
		prototype: HTMLElectionNavbarElement;
		new (): HTMLElectionNavbarElement;
	};
	interface HTMLElementTagNameMap {
		'election-navbar': HTMLElectionNavbarElement;
	}
}
declare namespace LocalJSX {
	interface ElectionNavbar {}
	interface IntrinsicElements {
		'election-navbar': ElectionNavbar;
	}
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
	export namespace JSX {
		interface IntrinsicElements {
			'election-navbar': LocalJSX.ElectionNavbar &
				JSXBase.HTMLAttributes<HTMLElectionNavbarElement>;
		}
	}
}
