/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
	interface ElectionButton {
		/**
		 * Disable button
		 */
		disabled: boolean;
	}
	interface ElectionFooter {}
	interface ElectionNavbar {}
}
declare global {
	interface HTMLElectionButtonElement
		extends Components.ElectionButton, HTMLStencilElement {}
	var HTMLElectionButtonElement: {
		prototype: HTMLElectionButtonElement;
		new (): HTMLElectionButtonElement;
	};
	interface HTMLElectionFooterElement
		extends Components.ElectionFooter, HTMLStencilElement {}
	var HTMLElectionFooterElement: {
		prototype: HTMLElectionFooterElement;
		new (): HTMLElectionFooterElement;
	};
	interface HTMLElectionNavbarElement
		extends Components.ElectionNavbar, HTMLStencilElement {}
	var HTMLElectionNavbarElement: {
		prototype: HTMLElectionNavbarElement;
		new (): HTMLElectionNavbarElement;
	};
	interface HTMLElementTagNameMap {
		'election-button': HTMLElectionButtonElement;
		'election-footer': HTMLElectionFooterElement;
		'election-navbar': HTMLElectionNavbarElement;
	}
}
declare namespace LocalJSX {
	interface ElectionButton {
		/**
		 * Disable button
		 */
		disabled?: boolean;
	}
	interface ElectionFooter {}
	interface ElectionNavbar {}
	interface IntrinsicElements {
		'election-button': ElectionButton;
		'election-footer': ElectionFooter;
		'election-navbar': ElectionNavbar;
	}
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
	export namespace JSX {
		interface IntrinsicElements {
			'election-button': LocalJSX.ElectionButton &
				JSXBase.HTMLAttributes<HTMLElectionButtonElement>;
			'election-footer': LocalJSX.ElectionFooter &
				JSXBase.HTMLAttributes<HTMLElectionFooterElement>;
			'election-navbar': LocalJSX.ElectionNavbar &
				JSXBase.HTMLAttributes<HTMLElectionNavbarElement>;
		}
	}
}
