import { ElectionFooter, ElectionNavbar } from '@election/ui/react';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="th">
			<head>
				<link
					href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai+Looped:wght@400;600;700&family=Sriracha&display=swap"
					rel="stylesheet"
				/>
				<link
					href="https://design-systems.wevis.info/typography.css"
					rel="stylesheet"
				/>
			</head>
			<body>
				<ElectionNavbar />
				{children}
				<ElectionFooter />
			</body>
		</html>
	);
}
